a = float(input("Digite el valor de A:"))
b = float(input("Digite el valor de B:"))
c = float(input("Digite el valor de C:"))
resultado = (a ** 3 * (b ** 2 - 2 * a * c)) / (2 * b)
print(f"El resultado es: {resultado}")
